---
- name: Add Documentation Directory
  file:
    path: "{{ code_doc_path_github }}"
    state: directory

- name: Add Project Pull Request Templates
  template:
    src: PULL_REQUEST.md.j2
    dest: "{{ code_doc_path_github }}/{{ item.value['name'] }}/"
  loop: "{{ project_list | dict2items }}"
