---
- name: Checkout Github Projects
  git:
    repo: "{{ item.value['repo'] }}"
    dest: "{{ code_checkout_path_github }}/{{ item.value['name'] }}"
    update: false
  loop: "{{ project_list | dict2items }}"

- name: Set direnv Files
  vars:
    direnv_file_contents: "{{ item.value['direnv'] | join('\n') }}"
  template:
    src: direnv.j2
    dest: "{{ code_checkout_path_github }}/{{ item.value['name'] }}/{{ direnv_filename }}"
  loop: "{{ project_list | dict2items }}"

#- name: Setup Project-Config Directory
#  file:
#    path: "{{ nvim_projects_dir }}/{{ item.value['name'] }}"
#    state: directory
#  loop: "{{ project_list | dict2items }}"

- name: Set vimlua Files
  vars:
    vimlua_file_contents: "{{ item.value['vimlua'] | join('\n') }}"
  template:
    src: vimlua.local.j2
    dest: "{{ nvim_projects_dir }}/{{ item.value['name'] }}.lua"
  loop: "{{ project_list | dict2items }}"

- name: Set vimrc Files
  vars:
    vimrc_file_contents: "{{ item.value['vimrc'] | join('\n') }}"
  template:
    src: vimrc.local.j2
    dest: "{{ nvim_projects_dir }}/{{ item.value['name'] }}.vim"
  loop: "{{ project_list | dict2items }}"

- name: Set Vim Tasks Files
  vars:
    tasks_file_contents: "{{ item.value['vim_tasks'] | join('\n') }}"
  template:
    src: tasks.j2
    dest: "{{ code_checkout_path_github }}/{{ item.value['name'] }}/{{ tasks_filename }}"
  loop: "{{ project_list | dict2items }}"
