---
- name: Install Toolbox
  import_tasks: install_toolbox.yml
  tags:
    - toolbox

- name: Setup Project-Config Directory
  file:
    path: "{{ nvim_projects_dir }}"
    state: directory

- name: Install Project Files
  import_tasks: install_project_files.yml
  tags:
    - vim
    - vscode

- name: Install Project Documentation Files
  import_tasks: install_doc_files.yml
  tags:
    - doc
