---
- name: Checkout Github Projects
  git:
    repo: "{{ item.value[repo] }}"
    dest: "{{ code_checkout_path_github }}/{{ item.value[name] }}"
  loop: "{{ project_list_github | dict2items }}"

- name: Set direnv Files
  vars:
    direnv_file_contents: "{{ item.value[direnv] | join('\n') }}"
  template:
    src: direnv.j2
    dest: "{{ code_checkout_path_github }}/{{ item.value[name] }}/.direnv"
  loop: "{{ project_list | dict2items }}"
